#-------------------------------
# Site Settings
title: The United Church of Canandaigua
description: The United Church is a wonderful church family with rich traditions and history in the community of Canandaigua, New York.
logo: /images/uc-logo.png # You can add own logo. For example "/images/logo.png".
logo_dark:
color_scheme: light # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "News"
      submenu:
      - url: "/news/"
        title: "News"
      - url: "https://uccdga.churchcenter.com/calendar?view=month"
        title: "Calendar"    
      - url: "/lamplighter/"
        title: "Lamplighter"
      - url: https://uccdga.churchcenter.com/registrations
        title: Sign Up
      - url: https://uccdga.churchcenter.com/home
        title: Weekly Highlights
    - title: "About"
      submenu:
      - url: "/staff/"
        title: "Staff"
      - url: "/history/"
        title: "History"
      - url: "/giving/"
        title: "Giving"
      - url: "/about/"
        title: "FAQs"
      - url: "/building/"
        title: "Building"
      - url: "/organ/"
        title: "Organ"
    - title: "Ministries"
      submenu:
        - url: "/family/"
          title: "Family"
        - url: "/care/"
          title: "Care"
        - url: "/missions"
          title: "Missions"
        - url: "/church-life/"
          title: "Church Life"
        - url: "/worship/"
          title: "Worship"
    - title: "Sunday Service"
      submenu:
        - url: "/stream/"
          title: "Live Stream"
        - url: "/video/"
          title: "Videos"
        - url: "/podcast/"
          title: "Podcast"
        - url: "/worship/"
          title: "Description"
        - url: "/bulletin"
          title: "Bulletins"

footer_menu_settings:
  menu_items:
    - url: "/about/"
      title: "About"
    - url: "/news/"
      title: "News"
    - url: "/staff/"
      title: "Staff"
    - url: "/stream/"
      title: "Live Stream"

mobile_menu_settings:
  menu_items:
    - url: "/about/"
      title: "About"
    - url: "/news/"
      title: "News"
    - url: "/staff/"
      title: "Staff"
    - url: "/stream/"
      title: "Live Stream"


# Call to action button
cta_button:
  enable: true
  cta_button_link: '/contact/'
  cta_button_text: Get in touch


#-------------------------------
# Hero Settings
hero:
  enable: false
  hero_title: The United Church is a wonderful church family with rich traditions and history in the community of Canandaigua, New York.
  hero_description: Join us at 8:45 AM and 11 AM each Sunday morning

hero_authors:
  enable: true
  hero_authors_description: Meet our wonderful staff


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: Latest


#-------------------------------
# Christmas Section Settings (edit in _includes/section-christmas.html)
christmas:
  enable: false


#-------------------------------
# Recommended Section Settings
recommended:
  enable: false
  recommended_title: Recommended
  recommended_tag: "Lifestyle"


#-------------------------------
# About Section Settings
about:
  enable: true
  about_title: Welcome
  about_subtitle: Sunday Services at 8:45 AM and 11 AM
  about_description: |
    The United Church is a wonderful church family with rich traditions and history in the community of Canandaigua, New York

    Our mission is: That All Might Know, Love, and Follow the Lord Jesus Christ as Their Personal Lord and Savior.

    We hope you will visit in person and learn more about our congregation. Please take a few minutes to read more about who we are and how we understand what it means to live out our faith.
  about_image: "/images/UC24_264.jpg"
  about_image_alt: The United Church
  about_button_text: Read More
  about_button_link: /about/


#-------------------------------
# Authors Section Settings
authors:
  enable: true
  authors_title: Top authors


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Stay Inspired Weekly. Your Friendly Dose of Tips & Insights!
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Footer Settings
footer_description: The United Church is a wonderful church family with rich traditions and history in the community of Canandaigua, New York

# Social Links
social:
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://www.facebook.com/unitedchurchcdga"}
# - {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
# - {icon: "fa-brands fa-tiktok", name: "Tiktok", link: "https://www.tiktok.com"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/the_united_church_new_york/"}
# - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# - {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://www.dribbble.com"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://www.youtube.com/@uccdga"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: movqozej # Add your form_id
  title: Contact Us
  description: If you have any questions about our church or would like more information, feel free to contact us—we’d be happy to help!
  button_text: Send now

# NOTE
# Nomod theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
