name: monthly-lamplighter

on:
  schedule:
    - cron: '50 21 28 * *'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  monthly-lamplighter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate
        run: bash ./scripts/update-publications-lamplighter.sh
      - name: Commit
        run: |
          git config --global user.name 'uccdga'
          git config --global user.email '110483520+uccdga@users.noreply.github.com'
          git commit -am "Add monthly lamplighter"
          git push
